SELECT r.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, 
    ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO i JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID
GROUP BY r.REST_ID
HAVING i.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, i.FAVORITES DESC;