-- 코드를 입력하세요
WITH 2021USERS AS (
    SELECT * 
    FROM USER_INFO 
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
    COUNT (DISTINCT 2021USERS.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT 2021USERS.USER_ID) / (SELECT COUNT(*) FROM 2021USERS), 1) AS PURCHASED_RATIO
    
FROM ONLINE_SALE
JOIN 2021USERS
ON ONLINE_SALE.USER_ID = 2021USERS.USER_ID

GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
