-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', f.BOARD_ID, '/', f.FILE_ID, 
              f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE f
JOIN USED_GOODS_BOARD b 
ON f.BOARD_ID = b.BOARD_ID
WHERE b.BOARD_ID = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (
        SELECT MAX(VIEWS)
        FROM USED_GOODS_BOARD
    )
)
ORDER BY f.FILE_ID DESC

#SELECT CONCAT("/home/grep/src/", B.BOARD_ID, "/", F.FILE_ID, 
#              F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
#FROM USED_GOODS_BOARD AS B
#JOIN USED_GOODS_FILE AS F 
#ON B.BOARD_ID = F.BOARD_ID
#WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
#ORDER BY F.FILE_ID DESC;