SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM((b.PRICE * bs.SALES)) AS TOTAL_SALES
FROM BOOK_SALES bs
JOIN BOOK b
ON bs.BOOK_ID = b.BOOK_ID 
JOIN AUTHOR a
ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE DATE_FORMAT(bs.SALES_DATE, '%Y-%m') = '2022-01'
#WHERE YEAR(s.SALES_DATE) = 2022 AND MONTH(s.SALES_DATE) = 1
GROUP BY b.CATEGORY, a.AUTHOR_ID
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC;